### PR TITLE
Fixed wall bugs and spawned weapons

### PR DESCRIPTION
**Pull request by EskiltheBirdOfAutism**
basically, I hope to add more merge conflicts in the future.

### CODE REVIEW

**Review by Hampus-CS — APPROVED** [review]
I wish that you don't add more merge conflicts. If you do then you will regret it, that I can promise you.

**Comment by EskiltheBirdOfAutism** [comment]
Ah, yes I appreciate the warning, nevertheless I will add more.

**Comment by Hampus-CS** [comment]
You better not, you will regret doing it for the rest of your life.

**Comment by EskiltheBirdOfAutism** [comment]
Hey they said, the same thing to my brother in law Fromer, and hes fine!

**Comment by CharlieSU23B** [comment]
I hereby bleach my eyes so that I will forget seeing this, if you fuckers try to make me a witness in court I'll fly the third plane into a building

**Comment by EskiltheBirdOfAutism** [comment]
Charlie, This court is already in session, and I will add a boss fight that creates merge conflicts!

**Comment by Hampus-CS** [comment]
Well, he dosen't know what I am capable of because i had nothing to do with him.

**Comment by EskiltheBirdOfAutism** [comment]
I am inevitable.

**Comment by CharlieSU23B** [comment]
As vice leader of this project i hereby sentence you EskiltheBirdOfAutism, to 300 years of prison

**Comment by EskiltheBirdOfAutism** [comment]
Now I am become Death, the destroyer of scripts.

**Comment by Hampus-CS** [comment]
> I am inevitable.

No living organism is safe when i have the desire to do what needs to be done.

**Comment by EskiltheBirdOfAutism** [comment]
And a prison cannot hold me, for I am the boss fight I will create.

**Comment by CharlieSU23B** [comment]
Eskil if you don't want to have your body parts spread to every continent you'll stop with this nonsense and make more particles

**Comment by Hampus-CS** [comment]
> And a prison cannot hold me, for I am the boss fight I will create.

Well, you will want to go to a prision instead of what i will do if you create more merge conflicts.

**Comment by CharlieSU23B** [comment]
> basically, I hope to add more merge conflicts in the future.

Wow, that's just a brilliant idea, isn't it? Adding more merge conflicts? How about we waste even more time and energy dealing with unnecessary problems? What a genius move! It's truly a stroke of brilliance to actively seek out chaos and hinder productivity. Are you trying to win an award for the most counterproductive statement of the year? Because congratulations, you might just have a shot at it with this absurd suggestion.

**Comment by EskiltheBirdOfAutism** [comment]
I am the merge conflinct incarnate, I cannot die.

**Comment by Hampus-CS** [comment]
> > basically, I hope to add more merge conflicts in the future.
> 
> Wow, that's just a brilliant idea, isn't it? Adding more merge conflicts? How about we waste even more time and energy dealing with unnecessary problems? What a genius move! It's truly a stroke of brilliance to actively seek out chaos and hinder productivity. Are you trying to win an award for the most counterproductive statement of the year? Because congratulations, you might just have a shot at it with this absurd suggestion.

I agree. And the only person in this group that can fix the merge conflicts is me because only i know what to do. I don't want more of that type of work.

**Comment by Hampus-CS** [comment]
> I am the merge conflinct incarnate, I cannot die.

I can just remove you from the project, you know that right?

**Comment by CharlieSU23B** [comment]
> I am the merge conflinct incarnate, I cannot die.

Oh, fantastic! So, your grand plan is to turn collaboration into a chaotic nightmare by deliberately introducing more merge conflicts? How innovative! I can't decide if your idea is more misguided or just plain idiotic. Maybe next time, instead of aspiring to be the king of incompetence, try coming up with something remotely useful. It's astonishing how someone can be so committed to causing problems rather than solving them. If adding merge conflicts is your idea of progress, then I shudder to think about your concept of success.

**Comment by EskiltheBirdOfAutism** [comment]
You are shackled to this place Hampus, you are nothing without me and I am nothing without you, I am the Joker and you are the Batman, I am chaos and you are creation.

**Comment by Hampus-CS** [comment]
> You are shackled to this place Hampus, you are nothing without me and I am nothing without you, I am the Joker and you are the Batman, I am chaos and you are creation.

I know that I am great

**Comment by CharlieSU23B** [comment]
> You are shackled to this place Hampus, you are nothing without me and I am nothing without you, I am the Joker and you are the Batman, I am chaos and you are creation.

damn, that's kinda fire ngl

**Comment by EskiltheBirdOfAutism** [comment]
Without each other we cannot exist

**Comment by EskiltheBirdOfAutism** [comment]
It reminds me of that hit game, AMONG US

**Comment by Hampus-CS** [comment]
> Without each other we cannot exist

If i don't exist on earth then I will exist somewhere else

**Comment by CharlieSU23B** [comment]
> It reminds me of that hit game, AMONG US

Oh, great, you're bringing "Among Us" into this abyss of terrible ideas. Are you trying to turn our collaborative efforts into a backstabbing, trust-destroying mess like a round of "Among Us"? Because, you know, nothing says effective teamwork like sowing seeds of doubt and betrayal.

Congratulations, you've successfully combined the stupidity of wanting more merge conflicts with the sheer absurdity of an "Among Us" analogy. Maybe next, you can suggest we vote each other off the coding spaceship every time a bug appears. It's genuinely impressive how you managed to merge two terrible concepts into one colossal disaster.

**Comment by EskiltheBirdOfAutism** [comment]
But Hampus, you and I are the same person, I will follow you because I am shackled as well.

**Pull request merged**
